FROM quay.io/baselibrary/ubuntu:14.04
MAINTAINER ShawnMa <qsma@thoughtworks.com>

## Install packages
RUN \
  apt-get update && \
  apt-get install -y python3 python3-dev python3-pip &&\
  rm -rf /var/lib/apt/lists/*

