FROM baselibrary/ubuntu:14.04
MAINTAINER ShawnMa <qsma@thoughtworks.com>

## Install packages
RUN \
  apt-get update && \
  apt-get install -y python python-dev python-pip &&\
  rm -rf /var/lib/apt/lists/*

